os: linux
sudo: required
dist: trusty

language:
  - c

compiler:
  - gcc
  - clang

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libavl-dev libev-dev valgrind
  - pip install --user codecov
  
  - git clone git://git.cryptomilk.org/projects/cmocka.git
  - cd cmocka
  - git checkout tags/cmocka-1.0.1
  - mkdir build; cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make -j2 && sudo make install
  - cd ../..
  
  - git clone https://github.com/CESNET/libyang.git
  - cd libyang; mkdir build; cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=Release ..
  - make -j2 && sudo make install
  - cd ../..
  
  - git clone https://github.com/google/protobuf.git
  - cd protobuf
  - ./autogen.sh && ./configure --prefix=/usr && make -j2 && sudo make install
  - cd ..
  
  - git clone https://github.com/protobuf-c/protobuf-c.git
  - cd protobuf-c
  - ./autogen.sh && ./configure --prefix=/usr && make -j2 && sudo make install
  - cd ..

script:
  - mkdir build && cd build && cmake -DCMAKE_C_FLAGS=-Werror .. && make -j2 && ctest -V

after_success:
  - if [ "$CC" = "gcc" ]; then codecov; fi

env:
  global:
    # COVERITY_SCAN_TOKEN
    secure: RCZKKJbSgtqiQnLfjHscGK38UqR6ZRkh+zHfknhqTvHmTR5ghGzNkTnNRYKGy294YfF12+qVhKB+CXlFlgbliw8w2i8+RxVd9MWy2lZLQogDE3cBGR8tGal0v/dIWTUmh9zBw1M5fR6n4vn7D8VNPBbeqoThYzDaPv+I3Odcq0azoId7ahGkqUdvchy3WPunGnpUWeTmvnFsNEmaYgNIj4WjY6VglHMDLU9BPZRTyNR0pdtJzZ3KOQTXQXAI2xxwrXmu1cDIz4HsOQo+c5paPnozd2Sa7h3UwfG8tqxdeYn8jW+7EuYrdZWxgcbzAoZkuURqzERsFEjFHPwzn4q97FK50qeG2XjP4KPQEwbdOYr8Hgz2ISTr7ouOoKBj7P78sBbQKbMPq2xFxg+YH8SUAet/UowCsWARH/DSquuTCckirQb//bD22m8zTbLZqg/KnR7R0OoYwQr0LnTwSusZ5eRNluja5UHb8yB5PXekGBjv2VpHomN9myBlDR2Lm+2A1tbGWiMXRa2HfeGXRNGr26UWoNuXHzuadkUe+/dnfk1Fx+PaFxt2hkiO51/KdngWG101RXJZmMTurk+3/btPOLOB2IIZBNA/r5h2VJm2lwq/NmEm96AM72w5wwsGf2/q0V2ihQdCNfOTeNy7KQIU9Oxe5o5lCD2CI+HvCI0vXnk=

addons:
  coverity_scan:
    project:
      name: "sysrepo/sysrepo"
    notification_email: raszabo@cisco.com
    build_command_prepend: "mkdir build ; cd build ; cmake .. ; make clean"
    build_command:   "make"
    branch_pattern: coverity
